#! /bin/sh

case $# in
  1) ;; # continue
  *) printf '%s\n' "usage: $0 <dir>" >&2; exit 1;;
esac
find "$1" -type f -exec file {} + | cut -d: -f2 | cut -d, -f1 | sed 's/^[[:space:]]*//' | sort | uniq -c
