#! /usr/bin/env swipl
% vim: ft=prolog

:- module(zelda_scrape, [scrape/3,
                         zelda_sites/1,
                         zelda_image/2,
                         zelda_images/2,
                         zelda_all_images/2]).

:- use_module(library(http/http_open)). % http_open/3
:- use_module(library(sgml)). % load_html/3
:- use_module(library(xpath)). % xpath/3
:- use_module(library(apply)). % maplist/3, foldl/4
:- use_module(library(ordsets)). % ord_union/3
:- use_module(library(url)). % is_absolute_url/1
:- use_module(library(uri)). % uri_resolve/3

:- initialization(main, main).

scrape(Site, Path, Result) :-
    http_open(Site, S, []),
    load_html(stream(S), DOM, []),
    xpath(DOM, Path, Result).

zelda_sites([
    url_game('https://www.zeldadungeon.net/the-legend-of-zelda-walkthrough/the-gathering/', 'The Legend of Zelda'),
    url_game('https://www.zeldadungeon.net/the-legend-of-zelda-walkthrough/level-1-the-eagle/', 'The Legend of Zelda'),
    url_game('https://www.zeldadungeon.net/the-legend-of-zelda-walkthrough/level-2-the-moon/', 'The Legend of Zelda'),
    url_game('https://www.zeldadungeon.net/the-legend-of-zelda-walkthrough/level-3-the-manji/', 'The Legend of Zelda'),
    url_game('https://www.zeldadungeon.net/the-legend-of-zelda-walkthrough/level-4-the-snake/', 'The Legend of Zelda'),
    url_game('https://www.zeldadungeon.net/the-legend-of-zelda-walkthrough/level-5-the-lizard/', 'The Legend of Zelda'),
    url_game('https://www.zeldadungeon.net/the-legend-of-zelda-walkthrough/level-6-the-dragon/', 'The Legend of Zelda'),
    url_game('https://www.zeldadungeon.net/the-legend-of-zelda-walkthrough/level-7-the-demon/', 'The Legend of Zelda'),
    url_game('https://www.zeldadungeon.net/the-legend-of-zelda-walkthrough/level-8-the-lion/', 'The Legend of Zelda'),
    url_game('https://www.zeldadungeon.net/the-legend-of-zelda-walkthrough/level-9-death-mountain/', 'The Legend of Zelda'),
    url_game('https://www.zeldadungeon.net/the-adventure-of-link-walkthrough/parapa-palace/', 'Adventure of Link'),
    url_game('https://www.zeldadungeon.net/the-adventure-of-link-walkthrough/midoro-palace/', 'Adventure of Link'),
    url_game('https://www.zeldadungeon.net/the-adventure-of-link-walkthrough/island-palace/', 'Adventure of Link'),
    url_game('https://www.zeldadungeon.net/the-adventure-of-link-walkthrough/maze-palace/', 'Adventure of Link'),
    url_game('https://www.zeldadungeon.net/the-adventure-of-link-walkthrough/ocean-palace/', 'Adventure of Link'),
    url_game('https://www.zeldadungeon.net/the-adventure-of-link-walkthrough/hidden-palace/', 'Adventure of Link'),
    url_game('https://www.zeldadungeon.net/the-adventure-of-link-walkthrough/great-palace/', 'Adventure of Link'),
    url_game('https://www.zeldadungeon.net/a-link-to-the-past-walkthrough/zeldas-rescue/', 'A Link to the Past'),
    url_game('https://www.zeldadungeon.net/a-link-to-the-past-walkthrough/eastern-palace/', 'A Link to the Past'),
    url_game('https://www.zeldadungeon.net/a-link-to-the-past-walkthrough/desert-palace/', 'A Link to the Past'),
    url_game('https://www.zeldadungeon.net/a-link-to-the-past-walkthrough/tower-of-hera/', 'A Link to the Past'),
    url_game('https://www.zeldadungeon.net/a-link-to-the-past-walkthrough/hyrule-castle-tower/', 'A Link to the Past'),
    url_game('https://www.zeldadungeon.net/a-link-to-the-past-walkthrough/dark-palace/', 'A Link to the Past'),
    url_game('https://www.zeldadungeon.net/a-link-to-the-past-walkthrough/swamp-palace/', 'A Link to the Past'),
    url_game('https://www.zeldadungeon.net/a-link-to-the-past-walkthrough/skull-woods/', 'A Link to the Past'),
    url_game('https://www.zeldadungeon.net/a-link-to-the-past-walkthrough/gargoyles-domain/', 'A Link to the Past'),
    url_game('https://www.zeldadungeon.net/a-link-to-the-past-walkthrough/ice-palace/', 'A Link to the Past'),
    url_game('https://www.zeldadungeon.net/a-link-to-the-past-walkthrough/misery-mire/', 'A Link to the Past'),
    url_game('https://www.zeldadungeon.net/a-link-to-the-past-walkthrough/turtle-rock/', 'A Link to the Past'),
    url_game('https://www.zeldadungeon.net/a-link-to-the-past-walkthrough/ganons-tower/', 'A Link to the Past'),
    url_game('https://www.zeldadungeon.net/links-awakening-walkthrough/tail-cave/', 'Link\'s Awakening'),
    url_game('https://www.zeldadungeon.net/links-awakening-walkthrough/bottle-grotto/', 'Link\'s Awakening'),
    url_game('https://www.zeldadungeon.net/links-awakening-walkthrough/key-cavern/', 'Link\'s Awakening'),
    url_game('https://www.zeldadungeon.net/links-awakening-walkthrough/anglers-tunnel/', 'Link\'s Awakening'),
    url_game('https://www.zeldadungeon.net/links-awakening-walkthrough/catfishs-maw/', 'Link\'s Awakening'),
    url_game('https://www.zeldadungeon.net/links-awakening-walkthrough/face-shrine/', 'Link\'s Awakening'),
    url_game('https://www.zeldadungeon.net/links-awakening-walkthrough/eagles-tower/', 'Link\'s Awakening'),
    url_game('https://www.zeldadungeon.net/links-awakening-walkthrough/turtle-rock/', 'Link\'s Awakening'),
    url_game('https://www.zeldadungeon.net/links-awakening-walkthrough/the-awakening/', 'Link\'s Awakening'),
    url_game('https://www.zeldadungeon.net/ocarina-of-time-walkthrough/inside-the-great-deku-tree/', 'Ocarina of Time'),
    url_game('https://www.zeldadungeon.net/ocarina-of-time-walkthrough/princess-of-destiny/', 'Ocarina of Time'),
    url_game('https://www.zeldadungeon.net/ocarina-of-time-walkthrough/the-mighty-collection/', 'Ocarina of Time'),
    url_game('https://www.zeldadungeon.net/ocarina-of-time-walkthrough/dodongos-cavern/', 'Ocarina of Time'),
    url_game('https://www.zeldadungeon.net/ocarina-of-time-walkthrough/inside-jabu-jabus-belly/', 'Ocarina of Time'),
    url_game('https://www.zeldadungeon.net/ocarina-of-time-walkthrough/timely-appearance/', 'Ocarina of Time'),
    url_game('https://www.zeldadungeon.net/ocarina-of-time-walkthrough/forest-temple/', 'Ocarina of Time'),
    url_game('https://www.zeldadungeon.net/ocarina-of-time-walkthrough/fire-temple/', 'Ocarina of Time'),
    url_game('https://www.zeldadungeon.net/ocarina-of-time-walkthrough/ice-cavern/', 'Ocarina of Time'),
    url_game('https://www.zeldadungeon.net/ocarina-of-time-walkthrough/water-temple/', 'Ocarina of Time'),
    url_game('https://www.zeldadungeon.net/ocarina-of-time-walkthrough/bottom-of-the-well/', 'Ocarina of Time'),
    url_game('https://www.zeldadungeon.net/ocarina-of-time-walkthrough/shadow-temple/', 'Ocarina of Time'),
    url_game('https://www.zeldadungeon.net/ocarina-of-time-walkthrough/spirit-temple/', 'Ocarina of Time'),
    url_game('https://www.zeldadungeon.net/ocarina-of-time-walkthrough/ganons-castle/', 'Ocarina of Time'),
    url_game('https://www.zeldadungeon.net/majoras-mask-walkthrough/first-three-days/', 'Majora\'s Mask'),
    url_game('https://www.zeldadungeon.net/majoras-mask-walkthrough/southern-swamp/', 'Majora\'s Mask'),
    url_game('https://www.zeldadungeon.net/majoras-mask-walkthrough/woodfall-temple/', 'Majora\'s Mask'),
    url_game('https://www.zeldadungeon.net/majoras-mask-walkthrough/collection/', 'Majora\'s Mask'),
    url_game('https://www.zeldadungeon.net/majoras-mask-walkthrough/snowhead/', 'Majora\'s Mask'),
    url_game('https://www.zeldadungeon.net/majoras-mask-walkthrough/snowhead-temple/', 'Majora\'s Mask'),
    url_game('https://www.zeldadungeon.net/majoras-mask-walkthrough/spring-ranch-graveyard/', 'Majora\'s Mask'),
    url_game('https://www.zeldadungeon.net/majoras-mask-walkthrough/great-bay-and-zora-cape/', 'Majora\'s Mask'),
    url_game('https://www.zeldadungeon.net/majoras-mask-walkthrough/great-bay-temple/', 'Majora\'s Mask'),
    url_game('https://www.zeldadungeon.net/majoras-mask-walkthrough/ikana-canyon/', 'Majora\'s Mask'),
    url_game('https://www.zeldadungeon.net/majoras-mask-walkthrough/well-and-ikana-castle/', 'Majora\'s Mask'),
    url_game('https://www.zeldadungeon.net/majoras-mask-walkthrough/stone-tower-temple/', 'Majora\'s Mask'),
    url_game('https://www.zeldadungeon.net/majoras-mask-walkthrough/the-moon/', 'Majora\'s Mask'),
    url_game('https://www.zeldadungeon.net/oracle-of-seasons-walkthrough/gnarled-root-dungeon/', 'Oracle of Seasons'),
    url_game('https://www.zeldadungeon.net/oracle-of-seasons-walkthrough/snakes-remains/', 'Oracle of Seasons'),
    url_game('https://www.zeldadungeon.net/oracle-of-seasons-walkthrough/poison-moths-lair/', 'Oracle of Seasons'),
    url_game('https://www.zeldadungeon.net/oracle-of-seasons-walkthrough/dancing-dragon-dungeon/', 'Oracle of Seasons'),
    url_game('https://www.zeldadungeon.net/oracle-of-seasons-walkthrough/unicorns-cave/', 'Oracle of Seasons'),
    url_game('https://www.zeldadungeon.net/oracle-of-seasons-walkthrough/ancient-ruins/', 'Oracle of Seasons'),
    url_game('https://www.zeldadungeon.net/oracle-of-seasons-walkthrough/explorers-crypt/', 'Oracle of Seasons'),
    url_game('https://www.zeldadungeon.net/oracle-of-seasons-walkthrough/sword-and-shield-maze/', 'Oracle of Seasons'),
    url_game('https://www.zeldadungeon.net/oracle-of-seasons-walkthrough/onoxs-castle/', 'Oracle of Seasons'),
    url_game('https://www.zeldadungeon.net/oracle-of-seasons-walkthrough/room-of-rites/', 'Oracle of Seasons'),
    url_game('https://www.zeldadungeon.net/oracle-of-ages-walkthrough/spirits-grave/', 'Oracle of Ages'),
    url_game('https://www.zeldadungeon.net/oracle-of-ages-walkthrough/wing-dungeon/', 'Oracle of Ages'),
    url_game('https://www.zeldadungeon.net/oracle-of-ages-walkthrough/moonlit-grotto/', 'Oracle of Ages'),
    url_game('https://www.zeldadungeon.net/oracle-of-ages-walkthrough/skull-dungeon/', 'Oracle of Ages'),
    url_game('https://www.zeldadungeon.net/oracle-of-ages-walkthrough/crown-dungeon/', 'Oracle of Ages'),
    url_game('https://www.zeldadungeon.net/oracle-of-ages-walkthrough/mermaids-cave/', 'Oracle of Ages'),
    url_game('https://www.zeldadungeon.net/oracle-of-ages-walkthrough/jabu-jabus-belly/', 'Oracle of Ages'),
    url_game('https://www.zeldadungeon.net/oracle-of-ages-walkthrough/ancient-tomb/', 'Oracle of Ages'),
    url_game('https://www.zeldadungeon.net/oracle-of-ages-walkthrough/the-black-tower/', 'Oracle of Ages'),
    url_game('https://www.zeldadungeon.net/oracle-of-ages-walkthrough/spirits-grave/#', 'Oracle of Ages'),
    url_game('https://www.zeldadungeon.net/the-wind-waker-walkthrough/outset-island/', 'Wind Waker'),
    url_game('https://www.zeldadungeon.net/the-wind-waker-walkthrough/forsaken-fortress/', 'Wind Waker'),
    url_game('https://www.zeldadungeon.net/the-wind-waker-walkthrough/windfall-island/', 'Wind Waker'),
    url_game('https://www.zeldadungeon.net/the-wind-waker-walkthrough/dragon-roost-island/', 'Wind Waker'),
    url_game('https://www.zeldadungeon.net/the-wind-waker-walkthrough/dragon-roost-cavern/', 'Wind Waker'),
    url_game('https://www.zeldadungeon.net/the-wind-waker-walkthrough/forest-haven/', 'Wind Waker'),
    url_game('https://www.zeldadungeon.net/the-wind-waker-walkthrough/forbidden-woods/', 'Wind Waker'),
    url_game('https://www.zeldadungeon.net/the-wind-waker-walkthrough/nayrus-pearl/', 'Wind Waker'),
    url_game('https://www.zeldadungeon.net/the-wind-waker-walkthrough/tower-of-the-gods/', 'Wind Waker'),
    url_game('https://www.zeldadungeon.net/the-wind-waker-walkthrough/hyrule-castle/', 'Wind Waker'),
    url_game('https://www.zeldadungeon.net/the-wind-waker-walkthrough/earth-temple/', 'Wind Waker'),
    url_game('https://www.zeldadungeon.net/the-wind-waker-walkthrough/wind-temple/', 'Wind Waker'),
    url_game('https://www.zeldadungeon.net/the-wind-waker-walkthrough/the-triforce/', 'Wind Waker'),
    url_game('https://www.zeldadungeon.net/the-wind-waker-walkthrough/ganons-tower/', 'Wind Waker'),
    url_game('https://www.zeldadungeon.net/the-minish-cap-walkthrough/deepwood-shrine/', 'Minish Cap'),
    url_game('https://www.zeldadungeon.net/the-minish-cap-walkthrough/cave-of-flames/', 'Minish Cap'),
    url_game('https://www.zeldadungeon.net/the-minish-cap-walkthrough/fortress-of-winds/', 'Minish Cap'),
    url_game('https://www.zeldadungeon.net/the-minish-cap-walkthrough/temple-of-droplets/', 'Minish Cap'),
    url_game('https://www.zeldadungeon.net/the-minish-cap-walkthrough/palace-of-winds/', 'Minish Cap'),
    url_game('https://www.zeldadungeon.net/the-minish-cap-walkthrough/dark-hyrule-castle/', 'Minish Cap'),
    url_game('https://www.zeldadungeon.net/twilight-princess-walkthrough/ordon-village/', 'Twilight Princess'),
    url_game('https://www.zeldadungeon.net/twilight-princess-walkthrough/the-twilight/', 'Twilight Princess'),
    url_game('https://www.zeldadungeon.net/twilight-princess-walkthrough/faron-woods-twilight/', 'Twilight Princess'),
    url_game('https://www.zeldadungeon.net/twilight-princess-walkthrough/forest-temple/', 'Twilight Princess'),
    url_game('https://www.zeldadungeon.net/twilight-princess-walkthrough/kakariko-village-twilight/', 'Twilight Princess'),
    url_game('https://www.zeldadungeon.net/twilight-princess-walkthrough/death-mountain/', 'Twilight Princess'),
    url_game('https://www.zeldadungeon.net/twilight-princess-walkthrough/goron-mines/', 'Twilight Princess'),
    url_game('https://www.zeldadungeon.net/twilight-princess-walkthrough/lanayru-province-twilight/', 'Twilight Princess'),
    url_game('https://www.zeldadungeon.net/twilight-princess-walkthrough/lake-hylia-sidequests/', 'Twilight Princess'),
    url_game('https://www.zeldadungeon.net/twilight-princess-walkthrough/lakebed-temple/', 'Twilight Princess'),
    url_game('https://www.zeldadungeon.net/twilight-princess-walkthrough/the-master-sword/', 'Twilight Princess'),
    url_game('https://www.zeldadungeon.net/twilight-princess-walkthrough/gerudo-desert/', 'Twilight Princess'),
    url_game('https://www.zeldadungeon.net/twilight-princess-walkthrough/arbiters-grounds/', 'Twilight Princess'),
    url_game('https://www.zeldadungeon.net/twilight-princess-walkthrough/scaling-snowpeak/', 'Twilight Princess'),
    url_game('https://www.zeldadungeon.net/twilight-princess-walkthrough/snowpeak-ruins/', 'Twilight Princess'),
    url_game('https://www.zeldadungeon.net/twilight-princess-walkthrough/sacred-grove-round-two/', 'Twilight Princess'),
    url_game('https://www.zeldadungeon.net/twilight-princess-walkthrough/temple-of-time', 'Twilight Princess'),
    url_game('https://www.zeldadungeon.net/twilight-princess-walkthrough/in-search-of-the-sky/', 'Twilight Princess'),
    url_game('https://www.zeldadungeon.net/twilight-princess-walkthrough/city-in-the-sky/', 'Twilight Princess'),
    url_game('https://www.zeldadungeon.net/twilight-princess-walkthrough/palace-of-twilight/', 'Twilight Princess'),
    url_game('https://www.zeldadungeon.net/twilight-princess-walkthrough/cave-of-ordeals/', 'Twilight Princess'),
    url_game('https://www.zeldadungeon.net/twilight-princess-walkthrough/hyrule-castle/', 'Twilight Princess'),
    url_game('https://www.zeldadungeon.net/phantom-hourglass-walkthrough/mercay-island/', 'Phantom Hourglass'),
    url_game('https://www.zeldadungeon.net/phantom-hourglass-walkthrough/temple-of-fire/', 'Phantom Hourglass'),
    url_game('https://www.zeldadungeon.net/phantom-hourglass-walkthrough/ocean-king-part-II/', 'Phantom Hourglass'),
    url_game('https://www.zeldadungeon.net/phantom-hourglass-walkthrough/temple-of-wind/', 'Phantom Hourglass'),
    url_game('https://www.zeldadungeon.net/phantom-hourglass-walkthrough/ocean-king-part-III/', 'Phantom Hourglass'),
    url_game('https://www.zeldadungeon.net/phantom-hourglass-walkthrough/temple-of-courage/', 'Phantom Hourglass'),
    url_game('https://www.zeldadungeon.net/phantom-hourglass-walkthrough/ghost-ship/', 'Phantom Hourglass'),
    url_game('https://www.zeldadungeon.net/phantom-hourglass-walkthrough/ocean-king-part-IV/', 'Phantom Hourglass'),
    url_game('https://www.zeldadungeon.net/phantom-hourglass-walkthrough/goron-temple/', 'Phantom Hourglass'),
    url_game('https://www.zeldadungeon.net/phantom-hourglass-walkthrough/temple-of-ice/', 'Phantom Hourglass'),
    url_game('https://www.zeldadungeon.net/phantom-hourglass-walkthrough/ocean-king-part-v/', 'Phantom Hourglass'),
    url_game('https://www.zeldadungeon.net/phantom-hourglass-walkthrough/mutohs-temple/', 'Phantom Hourglass'),
    url_game('https://www.zeldadungeon.net/phantom-hourglass-walkthrough/ocean-king-part-vi/', 'Phantom Hourglass'),
    url_game('https://www.zeldadungeon.net/spirit-tracks-walkthrough/the-beginning/', 'Spirit Tracks'),
    url_game('https://www.zeldadungeon.net/spirit-tracks-walkthrough/the-forest-realm/', 'Spirit Tracks'),
    url_game('https://www.zeldadungeon.net/spirit-tracks-walkthrough/tower-of-spirits-2/', 'Spirit Tracks'),
    url_game('https://www.zeldadungeon.net/spirit-tracks-walkthrough/the-snow-realm/', 'Spirit Tracks'),
    url_game('https://www.zeldadungeon.net/spirit-tracks-walkthrough/tower-of-spirits-3/', 'Spirit Tracks'),
    url_game('https://www.zeldadungeon.net/spirit-tracks-walkthrough/the-ocean-realm/', 'Spirit Tracks'),
    url_game('https://www.zeldadungeon.net/spirit-tracks-walkthrough/tower-of-spirits-4/', 'Spirit Tracks'),
    url_game('https://www.zeldadungeon.net/spirit-tracks-walkthrough/the-fire-realm/', 'Spirit Tracks'),
    url_game('https://www.zeldadungeon.net/spirit-tracks-walkthrough/tower-of-spirits-5/', 'Spirit Tracks'),
    url_game('https://www.zeldadungeon.net/spirit-tracks-walkthrough/the-sand-realm/', 'Spirit Tracks'),
    url_game('https://www.zeldadungeon.net/spirit-tracks-walkthrough/tower-of-spirits-6/', 'Spirit Tracks'),
    url_game('https://www.zeldadungeon.net/spirit-tracks-walkthrough/the-dark-realm/', 'Spirit Tracks'),
    url_game('https://www.zeldadungeon.net/skyward-sword-walkthrough/skyloft/', 'Skyward Sword'),
    url_game('https://www.zeldadungeon.net/skyward-sword-walkthrough/faron-woods/', 'Skyward Sword'),
    url_game('https://www.zeldadungeon.net/skyward-sword-walkthrough/skyview-temple/', 'Skyward Sword'),
    url_game('https://www.zeldadungeon.net/skyward-sword-walkthrough/eldin-volcano/', 'Skyward Sword'),
    url_game('https://www.zeldadungeon.net/skyward-sword-walkthrough/earth-temple/', 'Skyward Sword'),
    url_game('https://www.zeldadungeon.net/skyward-sword-walkthrough/lanayru-desert/', 'Skyward Sword'),
    url_game('https://www.zeldadungeon.net/skyward-sword-walkthrough/lanayru-mining-facility/', 'Skyward Sword'),
    url_game('https://www.zeldadungeon.net/skyward-sword-walkthrough/isle-of-songs/', 'Skyward Sword'),
    url_game('https://www.zeldadungeon.net/skyward-sword-walkthrough/lake-floria/', 'Skyward Sword'),
    url_game('https://www.zeldadungeon.net/skyward-sword-walkthrough/ancient-cistern/', 'Skyward Sword'),
    url_game('https://www.zeldadungeon.net/skyward-sword-walkthrough/lanayru-sand-sea/', 'Skyward Sword'),
    url_game('https://www.zeldadungeon.net/skyward-sword-walkthrough/sandship/', 'Skyward Sword'),
    url_game('https://www.zeldadungeon.net/skyward-sword-walkthrough/volcano-summit/', 'Skyward Sword'),
    url_game('https://www.zeldadungeon.net/skyward-sword-walkthrough/fire-sanctuary/', 'Skyward Sword'),
    url_game('https://www.zeldadungeon.net/skyward-sword-walkthrough/thunderhead/', 'Skyward Sword'),
    url_game('https://www.zeldadungeon.net/skyward-sword-walkthrough/song-of-the-hero/', 'Skyward Sword'),
    url_game('https://www.zeldadungeon.net/skyward-sword-walkthrough/sky-keep/', 'Skyward Sword'),
    url_game('https://www.zeldadungeon.net/skyward-sword-walkthrough/final-showdown/', 'Skyward Sword'),
    url_game('https://www.zeldadungeon.net/a-link-between-worlds-walkthrough/eastern-palace/', 'Link Between Worlds'),
    url_game('https://www.zeldadungeon.net/a-link-between-worlds-walkthrough/house-of-gales/', 'Link Between Worlds'),
    url_game('https://www.zeldadungeon.net/a-link-between-worlds-walkthrough/tower-of-hera/', 'Link Between Worlds'),
    url_game('https://www.zeldadungeon.net/a-link-between-worlds-walkthrough/hyrule-castle/', 'Link Between Worlds'),
    url_game('https://www.zeldadungeon.net/a-link-between-worlds-walkthrough/thieves-hideout/', 'Link Between Worlds'),
    url_game('https://www.zeldadungeon.net/a-link-between-worlds-walkthrough/desert-palace/', 'Link Between Worlds'),
    url_game('https://www.zeldadungeon.net/a-link-between-worlds-walkthrough/dark-palace/', 'Link Between Worlds'),
    url_game('https://www.zeldadungeon.net/a-link-between-worlds-walkthrough/swamp-palace/', 'Link Between Worlds'),
    url_game('https://www.zeldadungeon.net/a-link-between-worlds-walkthrough/skull-woods/', 'Link Between Worlds'),
    url_game('https://www.zeldadungeon.net/a-link-between-worlds-walkthrough/turtle-rock/', 'Link Between Worlds'),
    url_game('https://www.zeldadungeon.net/a-link-between-worlds-walkthrough/ice-ruins/', 'Link Between Worlds'),
    url_game('https://www.zeldadungeon.net/a-link-between-worlds-walkthrough/lorule-castle/', 'Link Between Worlds'),
    url_game('https://www.zeldadungeon.net/breath-of-the-wild-walkthrough/great-plateau/', 'Breath of the Wild'),
    url_game('https://www.zeldadungeon.net/breath-of-the-wild-walkthrough/dueling-peaks/', 'Breath of the Wild'),
    url_game('https://www.zeldadungeon.net/breath-of-the-wild-walkthrough/hateno-village/', 'Breath of the Wild'),
    url_game('https://www.zeldadungeon.net/breath-of-the-wild-walkthrough/zoras-domain/', 'Breath of the Wild'),
    url_game('https://www.zeldadungeon.net/breath-of-the-wild-walkthrough/vah-ruta-dungeon/', 'Breath of the Wild'),
    url_game('https://www.zeldadungeon.net/breath-of-the-wild-walkthrough/goron-city/', 'Breath of the Wild'),
    url_game('https://www.zeldadungeon.net/breath-of-the-wild-walkthrough/vah-rudania-dungeon/', 'Breath of the Wild'),
    url_game('https://www.zeldadungeon.net/breath-of-the-wild-walkthrough/gerudo-town/', 'Breath of the Wild'),
    url_game('https://www.zeldadungeon.net/breath-of-the-wild-walkthrough/vah-naboris-dungeon/', 'Breath of the Wild'),
    url_game('https://www.zeldadungeon.net/breath-of-the-wild-walkthrough/rito-village/', 'Breath of the Wild'),
    url_game('https://www.zeldadungeon.net/breath-of-the-wild-walkthrough/vah-medoh-dungeon/', 'Breath of the Wild'),
    url_game('https://www.zeldadungeon.net/breath-of-the-wild-walkthrough/captured-memories/', 'Breath of the Wild'),
    url_game('https://www.zeldadungeon.net/breath-of-the-wild-walkthrough/the-master-sword/', 'Breath of the Wild'),
    url_game('https://www.zeldadungeon.net/breath-of-the-wild-walkthrough/hyrule-castle/', 'Breath of the Wild'),
    url_game('https://www.zeldadungeon.net/breath-of-the-wild-walkthrough/the-champions-ballad/', 'Breath of the Wild')
    ]).

zelda_image(url_game(Site, _), Link) :-
    scrape(Site, //img(@src), ImageLink),
    (
        % transform stuff like /a/relative/server/path
        % to Site/a/relative/server/path
        \+ is_absolute_url(ImageLink),
        uri_resolve(ImageLink, Site, Link)
    ;
        % otherwise keep as is
        is_absolute_url(ImageLink),
        ImageLink = Link
    ).

zelda_images(url_game(Site, Game), Links_Set) :-
    setof(image_game(Link, Game), zelda_image(url_game(Site, Game), Link), Links_Set).

zelda_all_images(Sites, Links_Set) :-
    maplist(zelda_images, Sites, List_Of_Links),
    foldl(ord_union, List_Of_Links, [], Links_Set).

run(Output) :-
    zelda_sites(Sites),
    zelda_all_images(Sites, Images),
    % length(Images, N),
    Output = Images.

write_image_game(image_game(Link, Game)) :-
    format('"~w","~w"~n', [Link, Game]).

main(_) :-
    run(Output),
    write('image_url,game'), nl,
    maplist(write_image_game, Output).
